---
  - name: updating system
    apt:
      upgrade: yes
      update_cache: yes
      
  - name: add key for docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add doker repository
    apt_repository:
      repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
      state: present

  - name: updating system
    apt:
      upgrade: yes
      update_cache: yes

  - name: installing docker-ce
    package: name=docker-ce state=latest

  - name: Add user(s) to "docker" group
    user:
      name: "{{ item }}"
      groups: "docker"
      append: true
    loop: "{{ docker__users }}"

  - name: copy Dockerfile
    copy:
      src: Dockerfile
      dest: /home/ubuntu/Dockerfile

  - name: copy list of plugins
    copy:
      src: plugins.txt
      dest: /home/ubuntu/plugins.txt
  
  - name: installing python-docker
    package: name=python-docker state=latest
  
  - name: build my jenkins image
    docker_image:
      name: myjenkins
      build:
        path: /home/ubuntu/
      source: build
      state: present

  - name: Create a docker jenkins container
    docker_container:
      name: myjenkins
      image: myjenkins
      ports:
        - "8080:8080"
        - "50000:50000"
      #volumes:
      #  - /var/jenkins_home:/home/ubuntu/jenkins
      state: started
